version: '3'

services:

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chat-app
      POSTGRES_PASSWORD: chat-app
      POSTGRES_DB: chat-app
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
      - ./db-config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
